version: '3.8'

services:

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - "8082:8082"
    networks:
      - user-network
    restart: unless-stopped

networks:
  user-network:
    name: user-network
    driver: bridge